openapi: 3.0.0
info:
  title: Itinerary API
  version: 1.0.0
  description: API documentation for Itinerary microservice
servers:
  - url: http://localhost:3000/api/v1
paths:
  /itineraries:
    get:
      summary: Get all itineraries
      tags:
        - Itinerary
      responses:
        '200':
          description: A list of itineraries
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    itinerary: success
                  message:
                    type: string
                    itinerary: Success!
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Itinerary'
                  appCode:
                    type: string
                    itinerary: OK
                  timestamp:
                    type: string
                    itinerary: '2023-10-01T12:00:00.000Z'
    post:
      summary: Create a new itinerary
      tags:
        - Itinerary
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewItinerary'
      responses:
        '201':
          description: The created itinerary
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    itinerary: success
                  message:
                    type: string
                    itinerary: Itinerary created successfully
                  data:
                    $ref: '#/components/schemas/Itinerary'
                  appCode:
                    type: string
                    itinerary: OK
                  timestamp:
                    type: string
                    itinerary: '2023-10-01T12:00:00.000Z'
  /itineraries/{id}:
    get:
      summary: Get a specific itinerary by ID
      tags:
        - Itinerary
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the itinerary to get
          schema:
            type: string
      responses:
        '200':
          description: The requested itinerary
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    itinerary: success
                  message:
                    type: string
                    itinerary: Success!
                  data:
                    $ref: '#/components/schemas/Itinerary'
                  appCode:
                    type: string
                    itinerary: OK
                  timestamp:
                    type: string
                    itinerary: '2023-10-01T12:00:00.000Z'
        '404':
          description: Itinerary not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    itinerary: error
                  message:
                    type: string
                    itinerary: Itinerary not found
                  appCode:
                    type: string
                    itinerary: UNKNOWN_ERROR
                  timestamp:
                    type: string
                    itinerary: '2023-10-01T12:00:00.000Z'
    put:
      summary: Update an existing itinerary by ID
      tags:
        - Itinerary
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the itinerary to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Itinerary'
      responses:
        '200':
          description: The updated itinerary
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    itinerary: success
                  message:
                    type: string
                    itinerary: Itinerary updated successfully
                  data:
                    $ref: '#/components/schemas/Itinerary'
                  appCode:
                    type: string
                    itinerary: OK
                  timestamp:
                    type: string
                    itinerary: '2023-10-01T12:00:00.000Z'
        '404':
          description: Itinerary not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    itinerary: error
                  message:
                    type: string
                    itinerary: Itinerary not found
                  appCode:
                    type: string
                    itinerary: UNKNOWN_ERROR
                  timestamp:
                    type: string
                    itinerary: '2023-10-01T12:00:00.000Z'
    delete:
      summary: Delete an itinerary by ID
      tags:
        - Itinerary
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the itinerary to delete
          schema:
            type: string
      responses:
        '204':
          description: Successfully deleted
        '404':
          description: Itinerary not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    itinerary: error
                  message:
                    type: string
                    itinerary: Itinerary not found
                  appCode:
                    type: string
                    itinerary: UNKNOWN_ERROR
                  timestamp:
                    type: string
                    itinerary: '2023-10-01T12:00:00.000Z'

  /itineraries/{itineraryId}/activities:
    post:
      summary: Add a new activity to an itinerary
      tags:
        - Itinerary
      parameters:
        - in: path
          name: itineraryId
          required: true
          description: ID of the itinerary
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Surfing
                description:
                  type: string
                  example: Surfing at the beach
                startDate:
                  type: string
                  format: date-time
                  example: '2022-12-02T00:00:00.000Z'
                endDate:
                  type: string
                  format: date-time
                  example: '2022-12-02T00:00:00.000Z'
                location:
                  type: object
                  properties:
                    latitude:
                      type: number
                      example: 37.7749
                    longitude:
                      type: number
                      example: -122.4194
                    address:
                      type: string
                      example: Fuengirola Beach
              required:
                - name
                - description
                - startDate
                - endDate
      responses:
        '201':
          description: Activity added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Activity added successfully
                  data:
                    $ref: '#/components/schemas/Activity'
                  appCode:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
    get:
      summary: Get all activities for a specific itinerary
      tags:
        - Itinerary
      parameters:
        - in: path
          name: itineraryId
          required: true
          description: ID of the itinerary
          schema:
            type: string
      responses:
        '200':
          description: A list of activities
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Success!
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Activity'
                  appCode:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
        '404':
          description: Itinerary not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Itinerary not found
                  appCode:
                    type: string
                    example: UNKNOWN_ERROR
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'

  /itineraries/{itineraryId}/activities/{activityId}:
    delete:
      summary: Delete an activity from an itinerary
      tags:
        - Itinerary
      parameters:
        - in: path
          name: itineraryId
          required: true
          description: ID of the itinerary
          schema:
            type: string
        - in: path
          name: activityId
          required: true
          description: ID of the activity
          schema:
            type: string
      responses:
        '204':
          description: Activity deleted successfully
        '404':
          description: Activity or itinerary not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Activity or itinerary not found
                  appCode:
                    type: string
                    example: UNKNOWN_ERROR
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
components:
  schemas:
    Itinerary:
      type: object
      properties:
        _id:
          type: string
          example: '60c72b2f9b1d8f0d8d0b6f9e'
        name:
          type: string
          example: Itinerary Name
        description:
          type: string
          example: A trip to the beach with friends
        startDate:
          type: string
          format: date-time
          example: '2022-12-01T00:00:00.000Z'
        endDate:
          type: string
          format: date-time
          example: '2022-12-05T00:00:00.000Z'
        createdAt:
          type: string
          format: date-time
          example: '2022-12-01T00:00:00.000Z'
        updatedAt:
          type: string
          format: date-time
          example: '2022-12-01T00:00:00.000Z'
        destinationId:
          type: number
          example: 1
        activities:
          type: array
          items:
            type: object
            properties:
              id:
                type: number
                example: 1
              itineraryId:
                type: number
                example: 1
              name:
                type: string
                example: Surfing
              description:
                type: string
                example: Surfing at the beach
              startDate:
                type: string
                format: date-time
                example: '2022-12-02T00:00:00.000Z'
              endDate:
                type: string
                format: date-time
                example: '2022-12-02T00:00:00.000Z'
              createdAt:
                type: string
                format: date-time
                example: '2022-12-01T00:00:00.000Z'
              updatedAt:
                type: string
                format: date-time
                example: '2022-12-01T00:00:00.000Z'
              location:
                type: object
                properties:
                  latitude:
                    type: number
                    example: 37.7749
                  longitude:
                    type: number
                    example: -122.4194
                  address:
                    type: string
                    example: Fuengirola Beach
        comments:
          type: array
          items:
            type: object
            properties:
              id:
                type: number
                example: 1
              itineraryId:
                type: number
                example: 1
              userId:
                type: number
                example: 1
              comment:
                type: string
                example: I loved the experience!
              createdAt:
                type: string
                format: date-time
                example: '2022-12-01T00:00:00.000Z'
              updatedAt:
                type: string
                format: date-time
                example: '2022-12-01T00:00:00.000Z'
        ratings:
          type: array
          items:
            type: object
            properties:
              id:
                type: number
                example: 1
              itineraryId:
                type: number
                example: 1
              userId:
                type: number
                example: 1
              rating:
                type: number
                example: 5
              createdAt:
                type: string
                format: date-time
                example: '2022-12-01T00:00:00.000Z'
              updatedAt:
                type: string
                format: date-time
                example: '2022-12-01T00:00:00.000Z'
      required:
        - name
        - description
        - startDate
        - endDate
        - destinationId
    NewItinerary:
      type: object
      properties:
        name:
          type: string
          example: Itinerary Name
        description:
          type: string
          example: A trip to the beach with friends
        startDate:
          type: string
          format: date-time
          example: '2022-12-01T00:00:00.000Z'
        endDate:
          type: string
          format: date-time
          example: '2022-12-05T00:00:00.000Z'
        destinationId:
          type: number
          example: 1
      required:
        - name
        - description
        - startDate
        - endDate
        - destinationId

    Activity:
      type: object
      properties:
        id:
          type: string
          example: 'activity12345'
        itineraryId:
          type: string
          example: '60c72b2f9b1d8f0d8d0b6f9e'
        name:
          type: string
          example: Surfing
        description:
          type: string
          example: Surfing at the beach
        startDate:
          type: string
          format: date-time
          example: '2022-12-02T00:00:00.000Z'
        endDate:
          type: string
          format: date-time
          example: '2022-12-02T00:00:00.000Z'
        createdAt:
          type: string
          format: date-time
          example: '2022-12-01T00:00:00.000Z'
        updatedAt:
          type: string
          format: date-time
          example: '2022-12-01T00:00:00.000Z'
        location:
          type: object
          properties:
            latitude:
              type: number
              example: 37.7749
            longitude:
              type: number
              example: -122.4194
            address:
              type: string
              example: Fuengirola Beach
      required:
        - name
        - description
        - startDate
        - endDate